name: Build llama-server

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt update && sudo apt install -y git cmake g++ build-essential

    - name: Build llama.cpp
      run: |
        mkdir build && cd build
        cmake .. -DLLAMA_BUILD_SERVER=ON -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: llama-server
        path: build/bin/llama-server
