name: Build main llama-server

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Reset GitHub Runner
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y

      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y git cmake g++ build-essential

      - name: Build llama.cpp with Static GLIBC
        run: |
          git clone https://github.com/ggerganov/llama.cpp.git
          cd llama.cpp
          mkdir build && cd build
          cmake .. -DLLAMA_BUILD_SERVER=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXE_LINKER_FLAGS="-static-libstdc++ -static-libgcc"
          cmake --build . --config Release

      - name: Upload Build Artifacts (llama-server + libllama.so + libggml.so)
        uses: actions/upload-artifact@v4  # Ensure you are using v4
        with:
          name: llama-build
          path: llama.cpp/build/
