name: Build main llama-server

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Reset GitHub Runner
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y

      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y git cmake g++ build-essential

      - name: Clone llama.cpp
        run: |
          git clone https://github.com/ggerganov/llama.cpp.git
          cd llama.cpp
          mkdir build && cd build
          cmake .. -DLLAMA_BUILD_SERVER=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: llama-server
          path: llama.cpp/build/
